---
- name: Install prerequisites
  block:
    - name: Install unzip if unzip is absent
      package:
        name: unzip
        state: present
    - name: Install PyGithub Python package
      pip:
        name: PyGithub
        state: present
