---
- name: Fetch latest run_id from the given build_type
  block:
    - name: Fetch latest run_id from the given build_type
      daeuniverse.general.github_workflow_run:
        owner: "{{ owner }}"
        repo: "{{ app }}"
        build_type: "{{ build_type }}"
      delegate_to: localhost
      register: result
      become: false
    - name: Extract run_id from outputs
      set_fact:
        run_id: "{{ result.run_id }}"
  when:
    - build_type is defined
    - latest
    - action_url is not defined

- name: Extract run_id from action_url
  set_fact:
    run_id: "{{ action_url | split('/') | last }}"
  when:
    - action_url is defined
    - build_type == "custom"

- name: Download binary from GitHub Actions
  get_url:
    url: "{{ base_url }}/{{ run_id }}/dae-linux-x86_64.zip"
    dest: /tmp/dae.zip
  register: download

- name: unzip dae.zip
  unarchive:
    remote_src: yes
    src: /tmp/dae.zip
    dest: /tmp

- name: Copy binary
  copy:
    remote_src: yes
    src: /tmp/dae-linux-x86_64
    dest: /usr/bin/dae
    mode: a+x

- name: Restart systemd service
  systemd:
    name: "{{ systemd_service }}"
    state: restarted
  when: download.changed

- name: Verify version
  block:
    - name: Verify version
      shell: |
        dae --version
      register: version
    - name: Print output
      debug:
        msg: "{{ version.stdout }}"
  when: download.changed
