---
- name: Check prerequisites
  block:
    - name: Gather package facts
      package_facts:
        manager: apt

    - name: Install jq if jq is absent
      apt:
        name: jq
        state: present
      when: '"jq" not in ansible_facts.packages'

    - name: Install curl if curl is absent
      apt:
        name: curl
        state: present
      when: '"curl" not in ansible_facts.packages'

    - name: Install unzip if unzip is absent
      apt:
        name: unzip
        state: present
      when: '"unzip" not in ansible_facts.packages'
